### PR TITLE
Update build

### PR DESCRIPTION
**Pull request by SuperQ**
* Update Go matrix to latest 3 versions.
* Update minimum Go version to 1.21.
* Update golangci-lint version.
* Update GitHub actions.
* Pin GitHub actions to hash, as recommended by OSSF.

### CODE REVIEW

**Comment by lestrrat** [comment]
I don't see why you need to specify a git commit ID for the actions. Is there any reason why you not just using `v4` or `v5` or whatever?

**Comment by SuperQ** [comment]
Pinning is generally [recommended by the OSSF](https://blog.rafaelgss.dev/why-you-should-pin-actions-by-commit-hash). Dependabot and similar will keep them up-to-date.

**Comment by SuperQ** [comment]
Ping, this would be nice to have to improve supply chain security.

**Comment by lestrrat** [comment]
@SuperQ Sorry, didn't see your reply until just now. Hmm, didn't know dependabot handles commit IDs.
I'll take your word for it.

Thanks!

**Comment by SuperQ** [comment]
Thanks for building this library. I'm thinking about using it [here](https://github.com/prometheus/snmp_exporter/pull/1234).

Time to cut a v1.1.0?

**Comment by lestrrat** [comment]
@SuperQ Yes, but not _right_ now. I know better than to cut a release when I'm about to go to bed...
Made myself a reminder to take a look in 12 hours :) 
image

**Comment by lestrrat** [comment]
done

**Pull request merged**
