### PR TITLE
Fix padding on hour clock.

### LINKED ISSUE #18: %I and %r should pad zero
## Description
As title, `%I` and `%r` should pad zero for 1-9.

## Sample code
```go
package main

import (
	"fmt"
	"log"
	"time"

	"github.com/lestrrat-go/strftime"
)

func main() {
	t := time.Date(2020, 07, 24, 9, 8, 7, 0, time.UTC)
	str, err := strftime.Format("%I:%M:%S %p", t)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(str) // 9:08:07 AM but should be 09:08:07 AM

	str, err = strftime.Format("%r", t)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(str) // 9:08:07 AM but should be 09:08:07 AM
}
```

For reference,
```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

int main(void)
{
  struct tm tm;
  char buf[255];

  memset(&tm, 0, sizeof(struct tm));
  strptime("09:08:07", "%T", &tm);
  strftime(buf, sizeof(buf), "%I %r", &tm);
  puts(buf); // 09 09:08:07 AM
}
```

### PR DESCRIPTION
**Pull request by lestrrat**
fixes #18

### CODE REVIEW

**Comment by lestrrat** [comment]
oops, forgot to look at %r

**Comment by lestrrat** [comment]
Ah, `%r = %I:%M:%S %p`, so it should be fixed too

**Comment by itchyny** [comment]
> Ah, %r = %I:%M:%S %p, so it should be fixed too

This is not correct. `%r` is defined by [`imsp`](https://github.com/lestrrat-go/strftime/blob/v1.0.2/specifications.go#L93), which has format [`3:04:05 PM`](https://github.com/lestrrat-go/strftime/blob/v1.0.2/appenders.go#L35).

**Comment by lestrrat** [comment]
Well, f*ck me. Thank you. Patch coming up.

**Comment by lestrrat** [comment]
@itchyny fix coming in #21, but I will finish it up later

**Pull request merged**
