### PR TITLE
Fix issue with optimization on verbatim value

### PR DESCRIPTION
**Pull request by lestrrat**
Apparently our tests did not include a case where there were multiple verbatim sections in a pattern, which made us oblivious to this issue. Moving the verbatim value inside the loop does the trick.

### CODE REVIEW

**Comment by aaronchipper** [comment]
Cool - will test. Can confirm the issue I found occurs if there are digits anywhere in the pattern, not just next to specifications..

**Comment by aaronchipper** [comment]
Not 100% sure this has fixed it. I may be wrong and am still using an older version, but I'm 99% sure I'm using the branch.

I have tested with a pattern of:
/home/aaron1/TestLogger1/log/TestLogger1/%Y%m%d/Test9Logger.%Y%m%d.%H.log.%H.log
and I'm still getting contracted output:
.log20191230.log20191230.18.log.18.log

Can I suggest you update the test to check the prefix up to the first specification? just checking for a "/" is probably not enough.

**Comment by aaronchipper** [comment]
Ok, good news. The problem was me, not you.
I have managed to get the RIGHT version this time and can confirm things are working as expected.
Thanks for the fast turnaround!

**Comment by aaronchipper** [comment]
I've created some new tests for this fix here:
https://gist.github.com/aaronchipper/d589b5b50d0eddc7227f3a72be05a2fb
 (Too lazy to clone and PR :-P )

**Comment by lestrrat** [comment]
Thanks, I'd include your test if it used a fixed time instead of `time.Now()`, which *could* potentially break at some instance in time :)

for now I'm just going to merge the PR as-is

**Comment by aaronchipper** [comment]
As a final thank you, I updated the test in the gist with a fixed date and simplified test (can just do simple equality check now).
https://gist.github.com/aaronchipper/d589b5b50d0eddc7227f3a72be05a2fb

Thank you kindly for fixing this so quickly. Your library is quite widely used; I'm surprised no-one picked up on this sooner.

**Comment by lestrrat** [comment]
Sorry for the late reply, holidays and what not. I've included your tests.

> Your library is quite widely used; I'm surprised no-one picked up on this sooner.

That's nice to know! thanks :)

**Comment by aaronchipper** [comment]
No issue - thanks again for the fast turnaround. We're using the library in prod again and all seems to be going well!

Cheers :-)

**Pull request merged**
